# JustAFK Configuration
tagmessages: true

# AFK-related options
autokick: true
hideawayplayers: true
broadcastawaymsg: true
movementcheckfreq: 30 #seconds
kicktime: 60 #seconds
kickreason: '&cYou were inactive for too long!'
kickwhileinvehicle: true